// projects/react/src/components/ParkVehicle.tsx
import { useState } from 'react';
import { parkVehicle, VehicleType, InitialParkingResponse } from '../services/carPark';

interface ParkVehicleProps {
  onVehicleParked: (response: InitialParkingResponse) => void;
  onParkError: (message: string) => void;
}

const ParkVehicle = ({ onVehicleParked, onParkError }: ParkVehicleProps) => {
  const [vehicleReg, setVehicleReg] = useState('');
  const [vehicleType, setVehicleType] = useState(VehicleType.SmallCar);
  const [isParking, setIsParking] = useState(false);

  const vehicleTypeOptions = [
    { name: 'SmallCar', value: VehicleType.SmallCar },
    { name: 'MediumCar', value: VehicleType.MediumCar },
    { name: 'LargeCar', value: VehicleType.LargeCar }
  ];

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!vehicleReg || isParking) return;

    setIsParking(true);
    try {
      const response = await parkVehicle({ vehicleReg, vehicleType });
      onVehicleParked(response);
      setVehicleReg('');
    } catch (error: any) {
      onParkError(error.message || 'An unknown error occurred while parking.');
    } finally {
      setIsParking(false);
    }
  };

  return (
    <article>
      <hgroup>
        <h2>Park a Vehicle</h2>
        <h3>Enter vehicle details to park.</h3>
      </hgroup>
      <form onSubmit={handleSubmit}>
        <label htmlFor="park-reg">Vehicle Registration</label>
        <input
          id="park-reg"
          value={vehicleReg}
          onChange={(e) => setVehicleReg(e.target.value)}
          placeholder="e.g., AB12 CDE"
          required
        />

        <label htmlFor="park-type">Vehicle Type</label>
        <select
          id="park-type"
          value={vehicleType}
          onChange={(e) => setVehicleType(Number(e.target.value))}
          required
        >
          {vehicleTypeOptions.map((type) => (
            <option key={type.value} value={type.value}>
              {type.name}
            </option>
          ))}
        </select>
        <button type="submit" disabled={!vehicleReg || isParking} aria-busy={isParking}>
          Park Vehicle
        </button>
      </form>
    </article>
  );
};

export default ParkVehicle;

// projects/angular/src/app/components/park-vehicle.component.ts
import { Component, EventEmitter, OnInit, Output, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { CarParkService, InitialParkingResponse, VehicleType } from '../services/car-park';

@Component({
  selector: 'app-park-vehicle',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <article>
      <hgroup>
        <h2>Park a Vehicle</h2>
        <h3>Enter vehicle details to park.</h3>
      </hgroup>
      <form [formGroup]="parkForm" (ngSubmit)="onSubmit()">
        <label for="park-reg">Vehicle Registration</label>
        <input id="park-reg" formControlName="vehicleReg" placeholder="e.g., AB12 CDE" required />

        <label for="park-type">Vehicle Type</label>
        <select id="park-type" formControlName="vehicleType" required>
          @for(type of vehicleTypeOptions; track type.value) {
            <option [value]="type.value">{{ type.name }}</option>
          }
        </select>
        <button type="submit" [disabled]="parkForm.invalid" [attr.aria-busy]="isParking">Park Vehicle</button>
      </form>
    </article>
  `
})
export class ParkVehicleComponent implements OnInit {
  private carParkService = inject(CarParkService);
  private fb = inject(FormBuilder);

  @Output() vehicleParked = new EventEmitter<InitialParkingResponse>();
  @Output() parkError = new EventEmitter<string>();

  parkForm!: FormGroup;
  isParking = false;
  vehicleTypeOptions = [
    { name: 'Car', value: VehicleType.Car },
    { name: 'Motorbike', value: VehicleType.Motorbike },
    { name: 'Van', value: VehicleType.Van }
  ];

  ngOnInit(): void {
    this.parkForm = this.fb.group({
      vehicleReg: ['', Validators.required],
      vehicleType: [VehicleType.Car, Validators.required]
    });
  }

  onSubmit(): void {
    if (this.parkForm.invalid || this.isParking) return;
    this.isParking = true;
    this.carParkService.parkVehicle(this.parkForm.value)
      .pipe(finalize(() => this.isParking = false))
      .subscribe({
        next: (res) => this.vehicleParked.emit(res),
        error: (err) => this.parkError.emit(err.error?.title || 'An unknown error occurred while parking.')
      });
  }
}
