// projects/angular/src/app/components/spaces-status.component.ts
import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CarParkService, SpacesResponse } from '../services/car-park';

@Component({
  selector: 'app-spaces-status',
  standalone: true,
  imports: [CommonModule],
  template: `
    <header>
      <h1>Car Park</h1>
      @if (spacesStatus) {
        <article>
          <p>Available Spaces: <strong>{{ spacesStatus.availableSpaces }}</strong></p>
          <p>Occupied Spaces: <strong>{{ spacesStatus.occupiedSpaces }}</strong></p>
        </article>
      } @else {
        <p><progress indeterminate></progress>Loading parking status...</p>
      }
    </header>
  `
})
export class SpacesStatusComponent implements OnInit {
  private carParkService = inject(CarParkService);
  public spacesStatus: SpacesResponse | null = null;

  ngOnInit(): void { this.refresh(); }

  public refresh(): void { this.carParkService.getSpacesStatus().subscribe(data => this.spacesStatus = data); }
}

// projects/react/src/components/SpacesStatus.tsx
import { useState, useEffect } from 'react';
import { getSpacesStatus, SpacesResponse } from '../services/carPark';

interface SpacesStatusProps {
  refresh: boolean;
}

const SpacesStatus = ({ refresh }: SpacesStatusProps) => {
  const [spacesStatus, setSpacesStatus] = useState<SpacesResponse | null>(null);

  useEffect(() => {
    const fetchStatus = async () => {
      try {
        const data = await getSpacesStatus();
        setSpacesStatus(data);
      } catch (error) {
        console.error('Failed to fetch spaces status:', error);
      }
    };

    fetchStatus();
  }, [refresh]);

  return (
    <header>
      <h1>Car Park</h1>
      {spacesStatus ? (
        <article>
          <p>Available Spaces: <strong>{spacesStatus.availableSpaces}</strong></p>
          <p>Occupied Spaces: <strong>{spacesStatus.occupiedSpaces}</strong></p>
        </article>
      ) : (
        <p><progress></progress>Loading parking status...</p>
      )}
    </header>
  );
};

export default SpacesStatus;
